POST http://localhost:4000/graphql HTTP/1.1
content-type: application/json
x-request-type: GraphQL

mutation {
    createUsers (
        body: [{
            name: "创建用户1122221231",
            account: "12121222212313",
            password: "121122212321"
        }],
        search: {}
    ){
        list {
            id
            name
            creator { name role { name } }
        }
        change {
            id
            name
            creator { name role { name } }
        }
    }
}
