POST http://localhost:4000/graphql HTTP/1.1
content-type: application/json
x-request-type: GraphQL

query{
    users{
        list {
          id
          name
          role { id name }
          creator { id name }
          updater { name role { name } }
        }
    }
}
