POST http://localhost:4000/api/graphql HTTP/1.1
content-type: application/json
x-request-type: GraphQL

query{
    userInfo{
      user {
        name
        role {
          id
          name
        }
      }
    }
}
