POST http://localhost:4000/graphql HTTP/1.1
content-type: application/json
x-request-type: GraphQL
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlMGM3NGIyYzRiMWI0MDExODMyMWFhYiIsIm5hbWUiOiLnrqHnkIblkZgiLCJyb2xlIjoiNWUwYzc0YjFjNGIxYjQwMTE4MzIxYWE2IiwiYWNjb3VudCI6ImFkbWluIiwiaWF0IjoxNjAwMzEwNjY1LCJleHAiOjE2MDAzOTcwNjV9.OVP02IT_gVx0o1LkNsVQqFuH6f8iz6xJr_u-dIpGqrAEJNRUdHiIjGYvCCLKSgIPqaeT1Urrcn7owdgw1IGrJxSqrpAYqnTOTNX70K9OxfWymMfRTDkygQRr_fCVVioFOyEw5zI1uv_gW-WzSVsQ1HZh-fITIg26mXZCqt_uOHibhmXQ57oM9-Jw_u90XYXgdw9gCiZgQJbhOw7HxCZ8y-rqHu89pPq2keDqrxPVYzsIMySIGUmo0ZC1tAsdBVT5laRFxTKM1IqS8JiftYuG-elkOXLSDF59RljQ-AfBZaWVq9KFX-Wt4C_ZAhm-lDSup4fZ3fwH5RTpiVZlemHwcA

query {
  kanbanGroups {
    list {
      id
      name
      desc
      kanban { id name desc }
      creator { id name role { id name auth } }
    }
  }
}
