POST http://localhost:4000/graphql HTTP/1.1
content-type: application/json
x-request-type: GraphQL

mutation {
  updateKanbanGroups (
    body: {
      name: "这是修改后 kanbanGroup 名称",
      desc: "这是修改后 kanbanGroup 的描述",
      kanban: "5f56fa1863c5f795e21bb7e4"
    }
    conds: { name: "这是修改后 kanbanGroup 名称" }
  ){
    list { id name desc }
    change { id name desc }
  }
}

