POST http://localhost:4000/graphql HTTP/1.1
content-type: application/json
x-request-type: GraphQL

mutation {
    createDiaries (
        body: [{
            name: "2019-08-03",
            getUp: "2019-08-03 22:22:22",
            toRest: "2019-08-03 22:22:22",
            diet: [
                { type: 1, desc: "鸡蛋" },
                { type: 2, desc: "鸡蛋" },
            ],
            fitness: [
                {
                    type: 1,
                    place: 1,
                    project: 1,
                    duration: 30,
                    feel: 1,
                },
            ],
            bill: [
                {
                    desc: "这是账单描述",
                    income: 1,
                    expend: 2,
                    balance: 100,
                }
            ],
            bodyIndex: {
                weight: 90,
                muscle: 90,
                moistureContent: 20,
                bodyfat: 40.25,
                bim: 40,
            },
            informalEssay: "随便说点什么"
        }]
    ){
        list { id  }
        change { id  }
    }
}
