POST http://localhost:4000/graphql HTTP/1.1
content-type: application/json
x-request-type: GraphQL

mutation {
    removeDiaries (
        conds: { name: "2019-08-03" }
    ){
        list { id  }
        change { id  }
    }
}
