POST http://localhost:4000/graphql HTTP/1.1
content-type: application/json
x-request-type: GraphQL
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlMGM3NGIyYzRiMWI0MDExODMyMWFhYiIsIm5hbWUiOiLnrqHnkIblkZgiLCJyb2xlIjoiNWUwYzc0YjFjNGIxYjQwMTE4MzIxYWE2IiwiYWNjb3VudCI6ImFkbWluIiwiaWF0IjoxNTgzMjkwNTYwLCJleHAiOjE1ODMzNzY5NjB9.DQrqXHcyGordJRy3yjd3a0W3qBzxAS8hECAdfDocqkqXC3o-vwLm5BYP4G_iSjHwxwLLxSr-YXjxdsjr-jfJLoNeKsE759AYQ8J54X9NEeNRxWEHd9ta-8mIJr3fRpCJuxfLF0FRjg2A-PQDoMEd2ZLWN6F19frEPR8qzPoHwoLPiiGNabA5bdtdOm9pZR5VobwW-ZQ6GJ1NwgBeBEkyWtYSjfBAfVu3h9Fleanv45BfnUechteK5quS6oo-8SDiTHocUaP8hD-_5m1Mwm08SgcEaibxDZuSzbXbSQNQts7WhIxNjaZ-ofpZ70yav5ER0xm03XCZPvhmGkDoQ-oiMw

query{
  statsBill(
    search: {
      name: ["2020-02-01","2020-02-03"],
      span: "week"
    }
  ){
    groupWithName {
      name
      income
      expend
      diaries { bill }
    }
  }
}
