POST http://localhost:4000/graphql HTTP/1.1
content-type: application/json
x-request-type: GraphQL
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlMGM3NGIyYzRiMWI0MDExODMyMWFhYiIsIm5hbWUiOiLnrqHnkIblkZgiLCJyb2xlIjoiNWUwYzc0YjFjNGIxYjQwMTE4MzIxYWE2IiwiYWNjb3VudCI6ImFkbWluIiwiaWF0IjoxNTg2MTM5ODEwLCJleHAiOjE1ODYyMjYyMTB9.NcJULgmMApD8PGQAYWbHXlztsNhz1WvokAvB7wNaSEZlHP64N-HPsoQaDyr7HRTTKzpLvoJagV6V7lV_jgeUsgl8rvnbXeorQ5p3SWB2qRUtXXv0JtaIQNYWhix4p7exKPPyVh5fS37BT220XpP2fOqjgI5jMolnKgc4VvAMqwo-JmoGIJLuI7hWAAHKGI-liLM2CzqZRZNw2FWeKc6NqcFjTpSJeD7CICzRjxqb_YkEBGdkY6Dxt6pzVpcnRSMeb5YQzBOzlwj-nUyOdkgFb9Lc8hNe_MBFGIuA4Ol5Se0mnIJM_YL74d6lVApIlQgpVb9wJ4ZPpkUFFZS_aZ-o8g

query{
  statsBill(
    search: {
      name: ["2019-02-01","2020-04-04-01"],
      span: "week"
    }
  ){
    groupWithName {
      name
      income
      expend
      diaries { bill }
    }
    stats
    message
  }
}
