# 链接收藏
extend type Query{
  linkHubs(
    orderBy: OrderBy
    search: LinkHubSearch
    pagination: Pagination
  ): LinkHubs
}

extend type Mutation{
  removeLinkHub (
    conds: LinkHubSearch!
    orderBy: OrderBy
    search: LinkHubSearch
    pagination: Pagination
  ): LinkHubs

  createLinkHub (
    body: [LinkHubFields!]!
    orderBy: OrderBy
    search: LinkHubSearch
    pagination: Pagination
  ): LinkHubs

  updateLinkHub (
    conds: LinkHubSearch!
    body: LinkHubUpdateFields!
    orderBy: OrderBy
    search: LinkHubSearch
    pagination: Pagination
  ): LinkHubs
}


type LinkHub {
  id: ID
  name: String
  link: String
  desc: String
  icon: String
  parent: LinkHub @relation

  creator: User @relation
  updater: User @relation
  updateTime: Date
  creationTime: Date
}

type LinkHubs{
  list: [LinkHub]
  change: [LinkHub]
  message: String
  pagination: Pagination
}

input LinkHubSearch {
  id: ID
  ids: [ID!]
  name: String
  link: String
  desc: String
  icon: String
  parent: ID
  creator: ID
  updater: ID
  startUpdateTime: Date
  endUpdateTime: Date
  startCreationTime: Date
  endCreationTime: Date
}

input LinkHubFields {
  name: String!
  link: String
  desc: String
  icon: String
  parent: ID
}

input LinkHubUpdateFields {
  name: String
  link: String
  desc: String
  icon: String
  parent: ID
}
