# 片段(短文)
extend type Query {
  snippets(
    orderBy: OrderBy
    search: SnippetSearch
    pagination: Pagination
  ): Snippets
}

extend type Mutation {
  createSnippets(
    body: [SnippetFields!]!
    orderBy: OrderBy
    search: SnippetSearch
    pagination: Pagination
  ): Snippets

  removeSnippets (
    conds: SnippetSearch!
    orderBy: OrderBy
    search: SnippetSearch
    pagination: Pagination
  ): Snippets

  updateSnippets (
    conds: SnippetSearch!
    body: SnippetFields!
    orderBy: OrderBy
    search: SnippetSearch
    pagination: Pagination
  ): Snippets
}

type Snippets {
  list: [Snippet]
  change: [Snippet]
  message: String
  pagination: Pagination
}

type Snippet {
  content: String
  tags: [Int]

  id: ID
  status: Int
  creator: User @relation
  updater: User @relation
  updateTime: Date
  creationTime: Date
}

input SnippetSearch {
  id: ID
  ids: [ID!]
  tags: [Int]
  content: String

  status: [Int]
  creator: ID
  updater: ID
  startUpdateTime: Date
  endUpdateTime: Date
  startCreationTime: Date
  endCreationTime: Date
}

input SnippetFields {
  tags: [Int]
  status: Int
  content: String
}
