POST http://localhost:4000/graphql HTTP/1.1
content-type: application/json
x-request-type: GraphQL
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlMGM3NGIyYzRiMWI0MDExODMyMWFhYiIsIm5hbWUiOiLnrqHnkIblkZgiLCJyb2xlIjoiNWUwYzc0YjFjNGIxYjQwMTE4MzIxYWE2IiwiYWNjb3VudCI6ImFkbWluIiwiaWF0IjoxNTg3NjkxMzczLCJleHAiOjE1ODc3Nzc3NzN9.IwHcqiLMAT1ymhh2T-h7PaR2ZDCpBcZBbXBlPP2eu1ePDKgra9SgHod1rHfxN2IzG4AcdPE6V0kX6D1QZFO8jgKpe1WPvGVM6UBnJFq1D9hR5HC-kt7T60rIL6jF9Pj6vlz9qZLblV-xqa5a20vMpZHVmyRQ9BkRdrtwiTpCqGGUoq1D1KRDqQB26kw0qj55OLOLmJ-JeQ-jR1LtsN7F00DG2sow4lipsKUReXN9B4vjCWp6VIlikskweCK7hcwUhAlLWB7XZOLLJYl7sBDw-Df0WJFj_ubbPehB3k3lrLB6TVFlRR90vrJQsyNOM1rO3av9YwAIxAN8xVWZGqiElw

mutation{
  createDatasetsfroms (
    body: [{
      value: 1,
      code: "status",
      desc: "描述1",
      name: "名称1",
    }]
  ){
    change {
      id
      name
      value
      code
      desc
      name
    }
  }
}
