POST http://localhost:4000/graphql HTTP/1.1
content-type: application/json
x-request-type: GraphQL

mutation{
  createDatasetsfroms (
    body: [{
      value: 1,
      code: "status",
      desc: "描述1",
      name: "名称1",
    }]
  ){
    change {
      id
      name
      value
      code
      desc
      name
    }
  }
}
