POST http://localhost:4000/graphql HTTP/1.1
content-type: application/json
x-request-type: GraphQL

query{
  datasetsfroms {
    list {
      id
      name
      code
      desc
      value
      creator { id name role { id name } }
      updater { id name }
      parent {
        id
        name
        code
        desc
        value
        parent {
          id
          name
          code
          desc
          value
          parent {
            id
            name
            code
            desc
            value
          }
        }
      }
    }
  }
}
