POST http://localhost:4000/graphql HTTP/1.1
content-type: application/json
x-request-type: GraphQL

mutation{
  removeDatasetsfroms (
    conds: { id: "5ea24403411a1a600c0c1c0b" }
  ){
    change {
      id
      name
      value
      code
      desc
      name
    }
  }
}
