version: '2'
services:
  mongo:
    build: ./mongo/
    container_name: blog-mongo
    environment:
      - TZ=Asia/Shanghai
    expose:
      - 27017
    volumes:
      - ./store/mongo/db:/data/db
      - ./store/mongo/configdb:/data/configdb
      - ./store/mongo/backups:/data/backups
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "20"
  node:
    build: ./node/
    container_name: blog-service
    ports:
      - 4000:4000
    links:
      - mongo
    environment:
      - NODE_ENV=production
      - TZ=Asia/Shanghai
    depends_on:
      - mongo
    command:
      - /bin/sh
      - -c
      - |
        pm2 start ecosystem.config.js && pm2 logs
    volumes:
      - ../:/var/service
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "20"
  web:
    image: nginx
    container_name: blog-web
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 80:80
    links:
      - node
    depends_on:
      - node
    volumes:
      - ../html/build:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./store/nginx/logs/:/var/log/nginx
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "20"
