version: '2'
services:
  mongo:
    build: ./mongo/
    container_name: blog-mongo
    environment:
      - TZ=Asia/Shanghai
    expose:
      - 27017
    volumes:
      - ./store/mongo/db:/data/db
      - ./store/mongo/configdb:/data/configdb
      - ./store/mongo/backups:/data/backups
      # 定时任务, 相关
      - ./mongo/cron:/var/spool/cron/crontabs
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "20"
  node:
    build: ./node/
    container_name: blog-service
    ports:
      - 4000:4000
    links:
      - mongo
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - mongo
    command: sh -c '/shell/waitfor.sh mongo:27017 -- npm run start:pro'
    volumes:
      - ../:/var/service
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "20"
  web:
    image: nginx
    container_name: blog-web
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 80:80
      - 443:443
    links:
      - node
    depends_on:
      - node
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ../src/app/static:/usr/share/nginx/html/service/static

      - ./store/nginx/logs/:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

      - ./nginx/ssl.pem:/etc/nginx/ssl.pem
      - ./nginx/ssl.key:/etc/nginx/ssl.key
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "20"
