version: '2'
logging:
  driver: "json-file"
  options:
    max-size: "100k"
    max-file: "20"
services:
  mongo:
    image: mongo
    container_name: blog-mongo
    expose:
      - 27017
    volumes:
      - ./store/mongo/db:/data/db
      - ./store/mongo/configdb:/data/configdb
  node:
    build: ./
    container_name: blog-service
    ports:
      - 4000:4000
    links:
      - mongo
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo
    command:
      - /bin/sh
      - -c
      - |
        pm2 start ecosystem.config.js && pm2 logs
    volumes:
      - ../:/var/service
  web:
    image: nginx
    container_name: blog-web
    ports:
      - 80:80
    links:
      - node
    depends_on:
      - node
    volumes:
      - ../html/build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./store/nginx/logs/:/var/log/nginx
