POST http://localhost:4000/graphql HTTP/1.1
content-type: application/json
x-request-type: GraphQL

mutation {
  updateKanbans (
    body: {
      name: "这是修改后kanban名称",
      desc: "这是修改后kanban的描述"
    }
    conds: {}
  ){
    list { id name }
    change { id name }
  }
}

