# 基础镜像: 表示在 ubuntu 镜像基础上进行扩展
FROM ubuntu

RUN rm /bin/sh && ln -s /bin/bash /bin/sh

# 创建工作目录
RUN mkdir /var/service

# 安装基本工具: wget、git、
RUN apt-get update && \
  apt-get install wget -y && \
  apt-get install git -y && \
  apt-get install build-essential libssl-dev -y

# 安装 nvm
RUN wget https://raw.githubusercontent.com/creationix/nvm/v0.30.1/install.sh | bash \
  && echo 'export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"' >> ~/.bashrc \
  && echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> ~/.bashrc \
  && nvm install node \
  && nvm alias default node

# 安装 netcat: 网络测试工具, 用于检测 mongo 容器运行状态
RUN apt-get -q update && apt-get -qy install netcat

# 拷贝脚本监听 mongo 容器
COPY ./waitfor.sh /shell/waitfor.sh
RUN chmod +x /shell/*

# 设置工作目录
WORKDIR /var/service

# 设置挂载点
VOLUME [/var/service]

# 对外暴露端口
EXPOSE 4000

# 容器启动时执行指令: 指定新建容器在每次运行时需要执行的命令
CMD /bin/bash
