# 基础镜像: 表示在 node 镜像基础上进行扩展, node 镜像中自带 git
FROM node

# 维护者信息: 填写维护者的信息
MAINTAINER qianyin qianyin95@gmai.com

# 镜像操作指令: https://registry.yarnpkg.com https://registry.npm.taobao.org/
RUN npm config set registry https://registry.yarnpkg.com && \
    npm install pm2 -g && \
    mkdir /var/service

# 设置 git 基本信息
RUN git config --global user.email "qianyin95@gmail.com" && \
    git config --global user.name "qianyin925"

# 设置工作目录
WORKDIR /var/service

# 设置挂载点
VOLUME [/var/service]

# 设置环境变量
ENV TZ Asia/Shanghai

# 对外暴露端口
EXPOSE 4000

# 容器启动时执行指令: 指定新建容器在每次运行时需要执行的命令
CMD /bin/bash
