# 基础镜像: 表示在 node 镜像基础上进行扩展
FROM node

# 维护者信息: 填写维护者的信息
MAINTAINER qianyin qianyin95@gmai.com

# 镜像操作指令: 
RUN npm config set registry https://registry.npm.taobao.org/ && \
    npm install pm2 -g && \
    mkdir /var/service

# 设置工作目录
WORKDIR /var/service

# 设置挂载点
VOLUME [/var/service]

# 对外暴露端口
EXPOSE 4000

# 容器启动时执行指令: 指定新建容器在每次运行时需要执行的命令
CMD /bin/bash
