POST http://localhost:4000/graphql HTTP/1.1
content-type: application/json
x-request-type: GraphQL

mutation {
    removeTags (
        conds: {
            name: "标签二"
        }
    ){
        list { id name }
        change { id name }
    }
}
