POST http://localhost:4000/graphql HTTP/1.1
content-type: application/json
x-request-type: GraphQL

query{
  tags(
    pagination: { current: 1, pageSize: 2 }
  ){
    list {
      id
      name
      creator { id name role { id name } }
      updater { id name role { id name } }
      parent { id name }
    }
  }
}
