# 用户
type Query {
  users(
    orderBy: OrderBy
    search: UserSearch
    pagination: Pagination
  ): Users!

  userInfo: UserInfo
}

type Mutation {
  createUsers(
    body: [UserFields!]!
    orderBy: OrderBy
    search: UserSearch
    pagination: Pagination
  ): Users

  removeUsers (
    conds: UserSearch!
    orderBy: OrderBy
    search: UserSearch
    pagination: Pagination
  ): Users

  updateUsers (
    conds: UserSearch!
    body: UserFields!
    orderBy: OrderBy
    search: UserSearch
    pagination: Pagination
  ): Users

  login (
    account: String
    password: String
  ): Login

}

type UserInfo {
  user: User
  message: String
}

type Login {
  user: User
  message: String
}

type Users {
  list: [User!]!
  change: [User!]!
  message: String
  pagination: Pagination
}

type User {
  bio: String
  avatar: String

  id: ID!
  name: String!
  account: String!

  sex: Int!
  role: Role! @relation

  creator: User! @relation
  updater: User! @relation
  updateTime: Date!
  creationTime: Date!
}

input UserSearch {
  id: ID
  ids: [ID!]
  name: String
  account: String
  role: ID
  sex: Int

  creator: ID
  updater: ID
  startUpdateTime: Date
  endUpdateTime: Date
  startCreationTime: Date
  endCreationTime: Date
}

input UserFields {
  name: String
  account: String
  password: String
  role: ID
  sex: Int
}
