# 照片: 图片
extend type Query {
  photos(
    orderBy: OrderBy
    search: PhotoSearch
    pagination: Pagination
  ): Photos
}

extend type Mutation {
   removePhotos (
    orderBy: OrderBy
    conds: PhotoSearch!
    search: PhotoSearch
    pagination: Pagination
  ): Photos

  # 单文件上传
  uploadPhotos(
    body: PhotoFields!
    orderBy: OrderBy
    search: PhotoSearch
    pagination: Pagination
  ): Photos!
}

input PhotoFields {
  type: Int
  payload: ID
  files: [Upload!]
}

type Photos {
  list: [Photo!]!
  change: [Photo!]!
  message: String
  pagination: Pagination
}

type Photo {
  id: ID!
  type: Int!
  url: String!
  name: String!
  sourceFileName: String!
  # payload

	status: Int!
  creator: User! @relation
  updater: User! @relation
  updateTime: Date!
  creationTime: Date!
}

input PhotoSearch {
  id: ID
  ids: [ID!]
  type: [Int]
  url: String
  name: String
  sourceFileName: String

  updater: ID
  creator: ID
  startUpdateTime: Date
  endUpdateTime: Date
  startCreationTime: Date
  endCreationTime: Date
  status: [Int]
}
