POST http://localhost:4000/graphql HTTP/1.1
content-type: application/json
x-request-type: GraphQL

mutation {
  updateKanbanTasks (
    body: {
      name: "这是修改后 kanbanTask 名称",
      desc: "这是修改后 kanbanTask 的描述",
      kanban: "5f56fa1863c5f795e21bb7e4",
      group: "5f56f82f7ba08191d057305b",
    }
    conds: { }
  ){
    list { id name desc }
    change { id name desc }
  }
}

