# 文章查询

POST http://localhost:4000/graphql HTTP/1.1
content-type: application/json
x-request-type: GraphQL

query{
  articles(
    search: { id: "5e0d11d9250091020206195b" }
    pagination: { current: 1, pageSize: 1 }
  ){
    list {
      id
      name
      creationTime
      tags { id name code value }
      creator { name role { name } }
      updater { name role { name id } }
    }
    pagination
  }
}

# tags { id name code value }
# creator { name role { name } }
