# 新增文章

POST http://localhost:4000/graphql HTTP/1.1
content-type: application/json
x-request-type: GraphQL

mutation {
  createArticles (
    body: [{
      name: "自定义文章"
    }]
  ){
    list { id name }
    change { id name }
  }
}
