# 文章发布

POST http://localhost:4000/graphql HTTP/1.1
content-type: application/json
x-request-type: GraphQL

mutation {
  releaseArticle (
    conds: {
        name: "自定义文章_修改"
    }
  ){
    list { id name }
    change { id name }
  }
}
