# 文章更新

POST http://localhost:4000/graphql HTTP/1.1
content-type: application/json
x-request-type: GraphQL
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlMGM3NGIyYzRiMWI0MDExODMyMWFhYiIsIm5hbWUiOiLnrqHnkIblkZgiLCJyb2xlIjoiNWUwYzc0YjFjNGIxYjQwMTE4MzIxYWE2IiwiYWNjb3VudCI6ImFkbWluIiwiaWF0IjoxNjAyNDg0NjU0LCJleHAiOjE2MDI1NzEwNTR9.QRz3NgWO-JfFBJhkYwJaiq-czonww4A-Oz_nyeRYRRYHAarIXGZmFHxpPl0TQhwxxz30hF-bcucKnHTej-AMOd9GhPGsXIVj1HwFOU08jJXGrzUzKbgZF95smtOb-gBHB8L06_ZhsvEVHCRXlHnMQvDNCUTICru3hyixAP4c4A1rezpd2obIhrWQHr7JlYHaqfaW6SUV5IA00WkGdPAueCLBHFoDTlu92aSetEFiyr37iIvNe1yiQrkPu0ptXk2XbFA_gpm3uX-5qixdxjG36Y7-Myg0cBRNWAJ5Ft-pWBJA7o6N2fRtMQuf71hcehhEEfocFIqYP-9CScR5JOg7wg

mutation {
  updateArticles (
    conds: {
      id: "5e0d11d9250091020206195b"
    }
    body: {
      name: "--------",
      tags: ["5f83bfd0499ff74793cfb214"],
    }
  ){
    list { id name }
    change { id name }
  }
}
