# 文章更新

POST http://localhost:4000/graphql HTTP/1.1
content-type: application/json
x-request-type: GraphQL

mutation {
  updateArticles (
    conds: {
      id: "5e0d11d9250091020206195b"
    }
    body: {
      name: "--------",
      tags: ["5f83bfd0499ff74793cfb214"],
    }
  ){
    list { id name }
    change { id name }
  }
}
