# 文章更新

POST http://localhost:4000/graphql HTTP/1.1
content-type: application/json
x-request-type: GraphQL
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlMGM3NGIyYzRiMWI0MDExODMyMWFhYiIsIm5hbWUiOiLnrqHnkIblkZgiLCJyb2xlIjoiNWUwYzc0YjFjNGIxYjQwMTE4MzIxYWE2IiwiYWNjb3VudCI6ImFkbWluIiwiaWF0IjoxNTc5NTg5Mjc0LCJleHAiOjE1Nzk2NzU2NzR9.J9eYUHY2uEpMTSqXZzBX_2-i87m4D1TjSmrIaZa4fMuWxnJe5xTf3420t4g5DgSllu4kvr7SjUgk_PzBevqpuTD3qS8k878LohqJr7hzHeRDOk1aY-pW0O9meFLdLgm9z06n1cOzO_5JFYksgbj4L4qzNZVY1TxE9K_E-OEuerEzn7yDMOwy0cQYLLh0sHL5jnv-H4T1CmXtyXacUZnaVHm-auQGf7tlr0Ii9bDbswSEBvdTcSZqHpTRZi5s4eST02GfHv-iWh38Oj8C7b9As-x2ZYYyGa5sN9qvdaL5myfHANG480Q4Tc7_xUHfoUx3wBVWXik_orFl95NJdu0DWQ

mutation {
  updateArticles (
    conds: {
      name: "自定义文章"
    }
    body: {
      name: "自定义文章_修改"
    }
  ){
    list { id name }
    change { id name }
  }
}
