POST http://localhost:4000/graphql HTTP/1.1
content-type: application/json
x-request-type: GraphQL

mutation {
  removeSnippets (
    conds: {
      id: "5ee712dff809f04d9d707da0"
    }
    search: {}
  ){
    list { id content }
    change { id content }
  }
}
