POST http://localhost:4000/graphql HTTP/1.1
content-type: application/json
x-request-type: GraphQL

mutation {
  createAlgorithms (
    body: [{
      content: "内-新增",
    }]
  ){
    list { id content }
    change { id content }
  }
}
