POST http://localhost:4000/graphql HTTP/1.1
content-type: application/json
x-request-type: GraphQL
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlMGM3NGIyYzRiMWI0MDExODMyMWFhYiIsIm5hbWUiOiLnrqHnkIblkZgiLCJyb2xlIjoiNWUwYzc0YjFjNGIxYjQwMTE4MzIxYWE2IiwiYWNjb3VudCI6ImFkbWluIiwiaWF0IjoxNjMzNTIzODg2LCJleHAiOjE2MzQxMjg2ODZ9.UFhyl_kwOR5juuI_Lcl8qrB__Hxf6aL0vFg1jBfsnv4Vewaphlj9FDu9DpN_L2PBB6RF_4x3RQRl-XnRIHVzCj-AGWBj1J7ShucEab397bdnCrIfkvWfFrrTxPMw8UU0PJBhETgG61BEzXHsIhN-kGVoBzpPT9JAesqgEZDgGLTR9MWz9lHn2z5FN7EioltJkTqGlpQTqRvZitsjz8lb_bqUz9GfiFlLmAYmdmjWUA9bEBDRUizwszF9y3UfVrWCFeqYdmYLvV7G2sgLEPqAwa-oeAJEsqOxbWvMkoFvjR6fBZFfNIsmlL1GzCFmox0Zunmy1oemDtA5RhgIWnmrfg

mutation {
  removeAlgorithms (
    conds: {}
    search: {}
  ){
    list { id content }
    change { id content }
  }
}
