POST http://localhost:4000/graphql HTTP/1.1
content-type: application/json
x-request-type: GraphQL
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlMGM3NGIyYzRiMWI0MDExODMyMWFhYiIsIm5hbWUiOiLnrqHnkIblkZgiLCJyb2xlIjoiNWUwYzc0YjFjNGIxYjQwMTE4MzIxYWE2IiwiYWNjb3VudCI6ImFkbWluIiwiaWF0IjoxNjQxMDkyMjE2LCJleHAiOjE2NDE2OTcwMTZ9.S6DzPHFRljbvkF2Xw__2neJNest2o74cuStgsP9XJeP3bSEG3F8N1drxrZYnUc6_X2nk556a7wfddaB1x00jSaCNn5HO1uTSL9spztTOiz5HV46iMRiUIlHg94fCRowMtZc_jOFjKHs_wEtyjS-YU22CxhMhh08NrQGczlVr-ZA-LRO0NPLLB79TdTi6TXkA0tIydETj3WR3ajJZeCbPKO1v2Y6b9Yz4CiQJF99frtgZtthE167fEBR0Gec53c83C9RnUS5zsU9Jc617x-6PpWYVOKHBblR3-iXswAbZHz-hG9Xbm1UmDOIjnb1Lw192YHjmDULq7mw6cOK6UC30Zg

query{
  test {
    name
    id
    status
    tag { name value code }
  }
  demo
}
